language: c
sudo: false
services:
 - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="bondi."
  matrix:
  - PACKAGE="bondi" DISTRO="debian-stable"   OCAML_VERSION="4.06.1"
  - PACKAGE="bondi" DISTRO="debian-stable"   OCAML_VERSION="4.05.0"
  - PACKAGE="bondi" DISTRO="debian-stable"   OCAML_VERSION="4.04.2"
  - PACKAGE="bondi" DISTRO="debian-unstable" OCAML_VERSION="4.03.0"
