version: 2
jobs:
  build-4.04:
    docker:
      - image: tmcgilchrist/ci-ocaml:ubuntu_xenial-4.04-20190624054323-375be29
    steps:
      - checkout
      - run:
          name: Build
          command: ./bin/ci

workflows:
  version: 2
  build:
    jobs:
      - build-4.04
